#pragma once

enum BarrierMessageHeader{
	HEADER_INVALID,
	REQ_CREATE_BARRIER, REQ_THREAD_ACHIEVED_BARRIER, 
	RES_NEW_BARRIER_CREATED, RES_BARRIER_ARLEADY_CREATED, 
	RES_ERR_BARRIER_ARLEADY_CREATED_WRONG_INITIAL_THREAD_COUNT, RES_ERR_BARRIER_NOT_FOUND, 
	RES_BARRIER_UP, RES_BARRIER_DOWN,
	REQ_ANNOUNCE_BARRIER_DOWN_LISTENING_PIPE,
	REQ_CLOSE_BARRIER, RES_BARRIER_CLOSED, RES_ANNOUNCE_OK
};